// ─── SkillLeague Trivia Question Bank ────────────────────────────────────────
//
// Categories:
//   sports     — players, teams, tournaments, results
//   culture    — geography, history, countries, cities
//   philosophy — figures, scientists, thinkers
//   religion   — factual knowledge only, no debate
//   visual     — visual deception with near-identical options
//
// Difficulty:
//   easy   → Division III  (attention + light deception)
//   medium → Division II   (precise knowledge)
//   hard   → Professional + Champions (exact details + maximum deception)

export interface TriviaQ {
  q:       string;    // full question text
  correct: string;    // exact correct answer
  opts:    string[];  // all 4 options INCLUDING the correct one
}

export const SPORTS_BANK: Record<'easy' | 'medium' | 'hard', TriviaQ[]> = {
  easy: [
    { q: "Which country won the FIFA World Cup in 2018?",               correct: "France",         opts: ["France",         "Croatia",        "Brazil",        "Germany"]         },
    { q: "Which sport uses a shuttlecock?",                              correct: "Badminton",      opts: ["Badminton",      "Tennis",         "Squash",        "Ping Pong"]       },
    { q: "How many players does each team field in soccer?",            correct: "11",             opts: ["11",             "10",             "9",             "12"]              },
    { q: "Which country is Cristiano Ronaldo from?",                    correct: "Portugal",       opts: ["Portugal",       "Spain",          "Brazil",        "Argentina"]       },
    { q: "In which sport is a 'slam dunk' performed?",                  correct: "Basketball",     opts: ["Basketball",     "Volleyball",     "Football",      "Baseball"]        },
    { q: "What is the highest belt color in karate?",                   correct: "Black",          opts: ["Black",          "Red",            "Gold",          "White"]           },
    { q: "Which country hosted the 2016 Summer Olympics?",              correct: "Brazil",         opts: ["Brazil",         "Japan",          "UK",            "China"]           },
    { q: "How many players are on a basketball court per team?",        correct: "5",              opts: ["5",              "6",              "7",             "11"]              },
    { q: "Which sport is played at Wimbledon?",                         correct: "Tennis",         opts: ["Tennis",         "Cricket",        "Badminton",     "Squash"]          },
    { q: "In which sport do players score a 'try'?",                    correct: "Rugby",          opts: ["Rugby",          "Cricket",        "American Football", "Hockey"]      },
    { q: "How often are the Summer Olympics held?",                     correct: "Every 4 years",  opts: ["Every 4 years",  "Every 2 years",  "Every 3 years", "Every 5 years"]   },
    { q: "Which country is Lionel Messi from?",                         correct: "Argentina",      opts: ["Argentina",      "Brazil",         "Spain",         "Chile"]           },
    { q: "What shape is a standard soccer pitch?",                      correct: "Rectangle",      opts: ["Rectangle",      "Circle",         "Square",        "Oval"]            },
    { q: "How many rings are on the Olympic flag?",                     correct: "5",              opts: ["5",              "4",              "6",             "7"]               },
  ],
  medium: [
    { q: "Who holds the record for most Grand Slam titles in men's tennis (2024)?",  correct: "Novak Djokovic",     opts: ["Novak Djokovic",     "Rafael Nadal",    "Roger Federer",   "Andy Murray"]        },
    { q: "In which year did the first FIFA World Cup take place?",                   correct: "1930",               opts: ["1930",               "1924",            "1934",            "1926"]               },
    { q: "Which country has won the most FIFA World Cup titles?",                    correct: "Brazil",             opts: ["Brazil",             "Germany",         "Italy",           "Argentina"]          },
    { q: "Which NBA player was nicknamed 'The Black Mamba'?",                        correct: "Kobe Bryant",        opts: ["Kobe Bryant",        "LeBron James",    "Michael Jordan",  "Shaquille O'Neal"]   },
    { q: "Which country won the 2022 FIFA World Cup?",                              correct: "Argentina",           opts: ["Argentina",          "France",          "Morocco",         "Croatia"]            },
    { q: "How many Olympic gold medals did Usain Bolt win in total?",               correct: "8",                  opts: ["8",                  "6",               "9",               "10"]                 },
    { q: "Which club did Lionel Messi spend the most years at?",                    correct: "FC Barcelona",        opts: ["FC Barcelona",       "PSG",             "Inter Miami",     "Manchester City"]    },
    { q: "What is the maximum break score in snooker?",                             correct: "147",                opts: ["147",                "136",             "155",             "140"]                },
    { q: "In which year did Muhammad Ali win his first World Heavyweight title?",   correct: "1964",               opts: ["1964",               "1960",            "1967",            "1970"]               },
    { q: "Which country does Roger Federer represent in tennis?",                   correct: "Switzerland",         opts: ["Switzerland",        "Sweden",          "Austria",         "Germany"]            },
    { q: "How long is a marathon race (rounded)?",                                  correct: "42 km",              opts: ["42 km",              "40 km",           "45 km",           "38 km"]              },
    { q: "Which team did LeBron James begin his NBA career with?",                  correct: "Cleveland Cavaliers", opts: ["Cleveland Cavaliers","Miami Heat",       "Los Angeles Lakers","Chicago Bulls"]    },
    { q: "Which sport awards the Stanley Cup?",                                     correct: "Ice Hockey",         opts: ["Ice Hockey",         "Basketball",       "Baseball",        "American Football"]  },
    { q: "How many players are on a volleyball team on the court?",                 correct: "6",                  opts: ["6",                  "5",               "7",               "9"]                  },
  ],
  hard: [
    { q: "In which year did Roger Federer win his first Wimbledon title?",                         correct: "2003",              opts: ["2003",              "2001",             "2004",             "2002"]              },
    { q: "Which country won the first Rugby World Cup in 1987?",                                   correct: "New Zealand",       opts: ["New Zealand",       "Australia",        "South Africa",     "England"]           },
    { q: "Who was the top scorer at the 2014 FIFA World Cup?",                                     correct: "James Rodríguez",   opts: ["James Rodríguez",   "Thomas Müller",    "Lionel Messi",     "Neymar"]            },
    { q: "In which year did Muhammad Ali defeat George Foreman in the 'Rumble in the Jungle'?",   correct: "1974",              opts: ["1974",              "1972",             "1976",             "1975"]              },
    { q: "Which team has won the most UEFA Champions League titles?",                              correct: "Real Madrid",       opts: ["Real Madrid",       "AC Milan",         "Bayern Munich",    "Barcelona"]         },
    { q: "How many times has Brazil won the FIFA World Cup?",                                      correct: "5",                 opts: ["5",                 "4",                "6",                "3"]                 },
    { q: "Which city hosted the 1908 Summer Olympics?",                                            correct: "London",            opts: ["London",            "Paris",            "Stockholm",        "Rome"]              },
    { q: "Who held the 100m world record immediately before Usain Bolt broke it?",                 correct: "Asafa Powell",      opts: ["Asafa Powell",      "Maurice Greene",   "Michael Johnson",  "Yohan Blake"]       },
    { q: "In which year was Michael Jordan first drafted by the Chicago Bulls?",                   correct: "1984",              opts: ["1984",              "1982",             "1986",             "1985"]              },
    { q: "Which swimmer has won the most Olympic gold medals in history?",                         correct: "Michael Phelps",    opts: ["Michael Phelps",    "Mark Spitz",       "Ian Thorpe",       "Ryan Lochte"]       },
    { q: "How many Formula 1 World Championships did Ayrton Senna win?",                          correct: "3",                 opts: ["3",                 "2",                "4",                "5"]                 },
    { q: "Which country finished 3rd place in the 2022 FIFA World Cup?",                          correct: "Croatia",           opts: ["Croatia",           "Morocco",          "Netherlands",      "Portugal"]          },
    { q: "In which year was the first Wimbledon Championship held?",                              correct: "1877",              opts: ["1877",              "1890",             "1868",             "1900"]              },
    { q: "Who was the first woman to win an Olympic gold medal in weightlifting?",                 correct: "Tara Nott",         opts: ["Tara Nott",         "Karnam Malleswari","Powerina Mun",     "Ding Meiyuan"]      },
  ],
};

export const CULTURE_BANK: Record<'easy' | 'medium' | 'hard', TriviaQ[]> = {
  easy: [
    { q: "What is the capital of France?",                             correct: "Paris",          opts: ["Paris",          "Rome",          "Madrid",        "Berlin"]         },
    { q: "Which is the largest continent by area?",                    correct: "Asia",           opts: ["Asia",           "Africa",        "Europe",        "North America"]  },
    { q: "What is the tallest mountain in the world?",                 correct: "Mount Everest",  opts: ["Mount Everest",  "K2",            "Mont Blanc",    "Kilimanjaro"]    },
    { q: "In which country is the Great Wall located?",               correct: "China",          opts: ["China",          "India",         "Japan",         "Korea"]          },
    { q: "What language is spoken in Brazil?",                         correct: "Portuguese",     opts: ["Portuguese",     "Spanish",       "English",       "French"]         },
    { q: "What is the capital of Japan?",                              correct: "Tokyo",          opts: ["Tokyo",          "Seoul",         "Beijing",       "Bangkok"]        },
    { q: "Which river is considered the longest in the world?",        correct: "Nile",           opts: ["Nile",           "Amazon",        "Mississippi",   "Yangtze"]        },
    { q: "What is the capital of Australia?",                          correct: "Canberra",       opts: ["Canberra",       "Sydney",        "Melbourne",     "Brisbane"]       },
    { q: "Which ocean is the largest?",                                correct: "Pacific Ocean",  opts: ["Pacific Ocean",  "Atlantic Ocean","Indian Ocean",  "Arctic Ocean"]   },
    { q: "What is the capital of Egypt?",                              correct: "Cairo",          opts: ["Cairo",          "Alexandria",    "Luxor",         "Giza"]           },
    { q: "How many continents are there on Earth?",                    correct: "7",              opts: ["7",              "5",             "6",             "8"]              },
    { q: "Which country is known as the Land of the Rising Sun?",      correct: "Japan",          opts: ["Japan",          "China",         "South Korea",   "Thailand"]       },
    { q: "What is the official language of Mexico?",                   correct: "Spanish",        opts: ["Spanish",        "Portuguese",    "French",        "English"]        },
    { q: "Which country has the Eiffel Tower?",                        correct: "France",         opts: ["France",         "Italy",         "Belgium",       "Germany"]        },
  ],
  medium: [
    { q: "Which ancient wonder of the world still exists today?",                      correct: "Great Pyramid of Giza",  opts: ["Great Pyramid of Giza","Hanging Gardens of Babylon","Colossus of Rhodes","Lighthouse of Alexandria"] },
    { q: "In what year did the Berlin Wall fall?",                                     correct: "1989",                   opts: ["1989",                 "1987",                 "1991",             "1990"]                         },
    { q: "What is the smallest country in the world by area?",                        correct: "Vatican City",           opts: ["Vatican City",         "Monaco",               "San Marino",       "Liechtenstein"]                },
    { q: "In which country were the first modern Olympic Games held?",                 correct: "Greece",                 opts: ["Greece",               "France",               "UK",               "USA"]                          },
    { q: "Which country has the most UNESCO World Heritage Sites?",                    correct: "Italy",                  opts: ["Italy",                "China",                "Spain",            "France"]                       },
    { q: "Which ancient civilization built Machu Picchu?",                            correct: "Inca",                   opts: ["Inca",                 "Aztec",                "Maya",             "Olmec"]                        },
    { q: "In which year did Christopher Columbus first reach the Americas?",          correct: "1492",                   opts: ["1492",                 "1488",                 "1497",             "1501"]                         },
    { q: "Which country is home to the ancient city of Petra?",                       correct: "Jordan",                 opts: ["Jordan",               "Egypt",                "Saudi Arabia",     "Israel"]                       },
    { q: "What was the name of the first artificial satellite launched into space?",   correct: "Sputnik",                opts: ["Sputnik",              "Apollo",               "Explorer",         "Vanguard"]                     },
    { q: "Which empire is considered the largest in history by land area?",           correct: "British Empire",         opts: ["British Empire",       "Mongol Empire",        "Roman Empire",     "Ottoman Empire"]               },
    { q: "Which country did Joan of Arc fight for?",                                  correct: "France",                 opts: ["France",               "England",              "Spain",            "Portugal"]                     },
    { q: "In which ocean is the Bermuda Triangle located?",                           correct: "Atlantic Ocean",         opts: ["Atlantic Ocean",       "Pacific Ocean",        "Indian Ocean",     "Caribbean Sea"]                },
    { q: "Which city was the capital of the Byzantine Empire?",                       correct: "Constantinople",         opts: ["Constantinople",       "Rome",                 "Athens",           "Alexandria"]                   },
    { q: "Which country has the longest coastline in the world?",                     correct: "Canada",                 opts: ["Canada",               "Russia",               "USA",              "Australia"]                    },
  ],
  hard: [
    { q: "In which year was the Magna Carta signed?",                                             correct: "1215",               opts: ["1215",              "1209",             "1220",             "1248"]              },
    { q: "In which city is the Uffizi Gallery located?",                                          correct: "Florence",           opts: ["Florence",          "Rome",             "Venice",           "Milan"]             },
    { q: "What was Istanbul called before being renamed by the Republic of Turkey in 1930?",      correct: "Constantinople",     opts: ["Constantinople",    "Byzantium",        "Ankara",           "Adrianople"]        },
    { q: "Which emperor ordered the construction of the Colosseum in Rome?",                     correct: "Vespasian",          opts: ["Vespasian",         "Nero",             "Augustus",         "Hadrian"]           },
    { q: "In which year did World War I begin?",                                                  correct: "1914",               opts: ["1914",              "1912",             "1916",             "1918"]              },
    { q: "What is the name of the strait between Europe and Africa?",                            correct: "Strait of Gibraltar", opts: ["Strait of Gibraltar","Strait of Messina","Strait of Dover", "Bosphorus"]         },
    { q: "In which year did the French Revolution begin?",                                        correct: "1789",               opts: ["1789",              "1776",             "1799",             "1793"]              },
    { q: "In which year did the Russian Revolution occur?",                                       correct: "1917",               opts: ["1917",              "1905",             "1921",             "1914"]              },
    { q: "Which war ended with the Treaty of Versailles?",                                        correct: "World War I",        opts: ["World War I",       "World War II",     "Napoleonic Wars",  "Franco-Prussian War"] },
    { q: "Which ancient civilization invented the concept of zero independently?",               correct: "Indian mathematicians", opts: ["Indian mathematicians","Babylonians","Chinese scholars","Egyptian scribes"] },
    { q: "In which year did the first moon landing occur?",                                       correct: "1969",               opts: ["1969",              "1967",             "1971",             "1965"]              },
    { q: "Who was the first pharaoh to unify Upper and Lower Egypt?",                            correct: "Menes (Narmer)",     opts: ["Menes (Narmer)",    "Ramesses II",      "Tutankhamun",      "Cleopatra"]         },
    { q: "What was the name of the ship that sank on its maiden voyage in 1912?",               correct: "Titanic",            opts: ["Titanic",           "Britannic",        "Olympic",          "Lusitania"]         },
    { q: "In which city was the Declaration of Independence signed in 1776?",                    correct: "Philadelphia",        opts: ["Philadelphia",      "New York",         "Boston",           "Washington D.C."]   },
  ],
};

export const PHILOSOPHY_BANK: Record<'easy' | 'medium' | 'hard', TriviaQ[]> = {
  easy: [
    { q: "Which philosopher said 'I think, therefore I am'?",                         correct: "René Descartes",  opts: ["René Descartes",  "Socrates",        "Plato",           "Aristotle"]        },
    { q: "Who discovered penicillin?",                                                 correct: "Alexander Fleming", opts: ["Alexander Fleming","Louis Pasteur",  "Joseph Lister",   "Edward Jenner"]    },
    { q: "Which scientist developed the theory of relativity?",                        correct: "Albert Einstein", opts: ["Albert Einstein",  "Isaac Newton",    "Niels Bohr",      "Max Planck"]       },
    { q: "What nationality was Leonardo da Vinci?",                                    correct: "Italian",         opts: ["Italian",          "French",          "Spanish",         "German"]           },
    { q: "Who wrote 'The Republic'?",                                                  correct: "Plato",           opts: ["Plato",            "Aristotle",       "Socrates",        "Pythagoras"]       },
    { q: "Who is known as the father of modern science?",                              correct: "Galileo Galilei", opts: ["Galileo Galilei",  "Isaac Newton",    "Albert Einstein", "Francis Bacon"]    },
    { q: "Who was the first woman to win a Nobel Prize?",                              correct: "Marie Curie",     opts: ["Marie Curie",      "Rosalind Franklin","Dorothy Hodgkin","Lise Meitner"]     },
    { q: "Which scientist is known for the laws of motion and gravity?",               correct: "Isaac Newton",    opts: ["Isaac Newton",     "Galileo Galilei", "Albert Einstein", "Johannes Kepler"]  },
    { q: "Who invented the telephone?",                                                correct: "Alexander Graham Bell", opts: ["Alexander Graham Bell","Thomas Edison","Nikola Tesla","Guglielmo Marconi"] },
    { q: "Who painted the Mona Lisa?",                                                 correct: "Leonardo da Vinci", opts: ["Leonardo da Vinci","Michelangelo",   "Raphael",         "Donatello"]        },
    { q: "Which ancient Greek is known for the Pythagorean theorem?",                 correct: "Pythagoras",      opts: ["Pythagoras",       "Euclid",          "Archimedes",      "Thales"]           },
    { q: "Who wrote 'A Brief History of Time'?",                                       correct: "Stephen Hawking", opts: ["Stephen Hawking",  "Carl Sagan",      "Neil deGrasse Tyson","Richard Feynman"] },
    { q: "Which Greek philosopher was the teacher of Alexander the Great?",           correct: "Aristotle",       opts: ["Aristotle",        "Plato",           "Socrates",        "Pythagoras"]       },
    { q: "Who discovered the structure of DNA alongside Watson?",                      correct: "Francis Crick",   opts: ["Francis Crick",    "Rosalind Franklin","Linus Pauling",  "Maurice Wilkins"]  },
  ],
  medium: [
    { q: "Which philosopher wrote 'Critique of Pure Reason'?",                        correct: "Immanuel Kant",      opts: ["Immanuel Kant",     "Friedrich Nietzsche","Georg Hegel",    "Arthur Schopenhauer"] },
    { q: "Who founded the philosophy of utilitarianism?",                              correct: "Jeremy Bentham",     opts: ["Jeremy Bentham",    "John Stuart Mill",  "John Locke",     "David Hume"]          },
    { q: "What nationality was Søren Kierkegaard?",                                   correct: "Danish",             opts: ["Danish",            "German",            "Norwegian",      "Swedish"]             },
    { q: "Who wrote 'Thus Spoke Zarathustra'?",                                        correct: "Friedrich Nietzsche",opts: ["Friedrich Nietzsche","Immanuel Kant",    "Arthur Schopenhauer","Martin Heidegger"] },
    { q: "Which philosopher is associated with the allegory of the cave?",            correct: "Plato",              opts: ["Plato",             "Aristotle",         "Socrates",       "Descartes"]           },
    { q: "In which century did Socrates live?",                                        correct: "5th century BC",     opts: ["5th century BC",    "4th century BC",    "3rd century BC", "6th century BC"]      },
    { q: "Who coined the phrase 'survival of the fittest'?",                          correct: "Herbert Spencer",    opts: ["Herbert Spencer",   "Charles Darwin",    "Thomas Huxley",  "Alfred Wallace"]      },
    { q: "Which philosopher founded the Lyceum school in Athens?",                    correct: "Aristotle",          opts: ["Aristotle",         "Plato",             "Socrates",       "Pythagoras"]          },
    { q: "Who wrote 'The Wealth of Nations'?",                                         correct: "Adam Smith",         opts: ["Adam Smith",        "David Ricardo",     "John Maynard Keynes","Friedrich Hayek"] },
    { q: "Who developed the heliocentric model of the solar system?",                 correct: "Nicolaus Copernicus",opts: ["Nicolaus Copernicus","Galileo Galilei",   "Johannes Kepler","Tycho Brahe"]         },
    { q: "What philosophical movement is associated with Jean-Paul Sartre?",          correct: "Existentialism",     opts: ["Existentialism",    "Phenomenology",     "Structuralism",  "Utilitarianism"]      },
    { q: "Who discovered the law of universal gravitation?",                           correct: "Isaac Newton",       opts: ["Isaac Newton",      "Albert Einstein",   "Galileo Galilei","Johannes Kepler"]     },
    { q: "Which philosopher argued that 'knowledge is virtue'?",                       correct: "Socrates",           opts: ["Socrates",          "Plato",             "Aristotle",      "Epicurus"]            },
    { q: "Who wrote 'The Prince', a guide for political rulers?",                      correct: "Niccolò Machiavelli",opts: ["Niccolò Machiavelli","Thomas More",      "Francis Bacon",  "John Locke"]          },
  ],
  hard: [
    { q: "Which philosopher wrote the 'Phenomenology of Spirit'?",                             correct: "Georg Hegel",           opts: ["Georg Hegel",          "Immanuel Kant",    "Karl Marx",        "Friedrich Nietzsche"]    },
    { q: "Who coined the term 'categorical imperative'?",                                      correct: "Immanuel Kant",         opts: ["Immanuel Kant",        "John Stuart Mill", "Jeremy Bentham",   "John Rawls"]             },
    { q: "What nationality was the philosopher Baruch Spinoza?",                               correct: "Dutch",                 opts: ["Dutch",                "German",           "Portuguese",       "French"]                 },
    { q: "Who wrote 'Being and Nothingness'?",                                                 correct: "Jean-Paul Sartre",      opts: ["Jean-Paul Sartre",     "Albert Camus",     "Simone de Beauvoir","Maurice Merleau-Ponty"] },
    { q: "What is the name of Plato's famous school in Athens?",                              correct: "The Academy",           opts: ["The Academy",          "The Lyceum",       "The Stoa",         "The Agora"]              },
    { q: "Who is considered the father of empiricism in modern philosophy?",                   correct: "Francis Bacon",         opts: ["Francis Bacon",        "René Descartes",   "John Locke",       "David Hume"]             },
    { q: "Which philosopher developed the concept of the 'veil of ignorance'?",               correct: "John Rawls",            opts: ["John Rawls",           "Robert Nozick",    "John Stuart Mill", "Immanuel Kant"]          },
    { q: "Who wrote 'Meditations on First Philosophy'?",                                       correct: "René Descartes",        opts: ["René Descartes",       "John Locke",       "David Hume",       "Baruch Spinoza"]         },
    { q: "Which ancient Greek philosopher taught that everything is made of water?",           correct: "Thales of Miletus",     opts: ["Thales of Miletus",    "Heraclitus",       "Anaximenes",       "Democritus"]             },
    { q: "In which year was the philosopher Immanuel Kant born?",                             correct: "1724",                  opts: ["1724",                 "1712",             "1740",             "1756"]                   },
    { q: "Which school of philosophy argued that virtue alone leads to happiness?",            correct: "Stoicism",              opts: ["Stoicism",             "Epicureanism",     "Cynicism",         "Skepticism"]             },
    { q: "Who wrote 'The Critique of Judgment'?",                                              correct: "Immanuel Kant",         opts: ["Immanuel Kant",        "Georg Hegel",      "Arthur Schopenhauer","David Hume"]           },
    { q: "Which philosopher introduced the concept of the 'Übermensch' (Superman)?",          correct: "Friedrich Nietzsche",   opts: ["Friedrich Nietzsche",  "Karl Marx",        "Martin Heidegger", "Albert Camus"]           },
    { q: "Who wrote 'Tractatus Logico-Philosophicus'?",                                        correct: "Ludwig Wittgenstein",   opts: ["Ludwig Wittgenstein",  "Bertrand Russell", "Gottlob Frege",    "Rudolf Carnap"]          },
  ],
};

export const RELIGION_BANK: Record<'easy' | 'medium' | 'hard', TriviaQ[]> = {
  easy: [
    { q: "How many pillars are there in Islam?",                                 correct: "5",                   opts: ["5",                   "4",                   "6",                 "7"]                    },
    { q: "What is the holy book of Muslims called?",                             correct: "The Quran",           opts: ["The Quran",           "The Bible",           "The Torah",         "The Vedas"]            },
    { q: "What is the holiest city in Islam?",                                   correct: "Mecca",               opts: ["Mecca",               "Medina",              "Jerusalem",         "Baghdad"]              },
    { q: "In which city was Jesus born according to scripture?",                 correct: "Bethlehem",           opts: ["Bethlehem",           "Jerusalem",           "Nazareth",          "Jericho"]              },
    { q: "Which religion has the most followers worldwide?",                     correct: "Christianity",        opts: ["Christianity",        "Islam",               "Hinduism",          "Buddhism"]             },
    { q: "What is the sacred river in Hinduism?",                                correct: "The Ganges",          opts: ["The Ganges",          "Nile",                "Euphrates",         "Indus"]                },
    { q: "Who founded Buddhism?",                                                correct: "Siddhartha Gautama",  opts: ["Siddhartha Gautama",  "Confucius",           "Lao Tzu",           "Mahavira"]             },
    { q: "In which direction do Muslims face when praying?",                     correct: "Toward Mecca",        opts: ["Toward Mecca",        "Toward Jerusalem",    "East",              "North"]                },
    { q: "What is the name of the Jewish day of rest?",                          correct: "Shabbat",             opts: ["Shabbat",             "Passover",            "Hannukah",          "Purim"]                },
    { q: "What is the Islamic holy month of fasting called?",                    correct: "Ramadan",             opts: ["Ramadan",             "Sha'ban",             "Muharram",          "Dhul Hijjah"]          },
    { q: "What is the holy book of Christians called?",                          correct: "The Bible",           opts: ["The Bible",           "The Torah",           "The Quran",         "The Vedas"]            },
    { q: "How many times a day do Muslims pray?",                                correct: "5",                   opts: ["5",                   "3",                   "7",                 "4"]                    },
    { q: "What is the Vatican?",                                                 correct: "The center of the Catholic Church", opts: ["The center of the Catholic Church","A city in Italy","A museum in Rome","The Pope's birthplace"] },
    { q: "Which religion observes Diwali, the festival of lights?",             correct: "Hinduism",            opts: ["Hinduism",            "Buddhism",            "Sikhism",           "Jainism"]              },
  ],
  medium: [
    { q: "Who was the first caliph of Islam after the Prophet Muhammad?",          correct: "Abu Bakr",                    opts: ["Abu Bakr",                    "Umar",                     "Uthman",                "Ali"]                          },
    { q: "What are the five books of Moses called collectively?",                  correct: "Torah",                       opts: ["Torah",                       "Talmud",                   "Midrash",               "Gemara"]                       },
    { q: "In which language was the New Testament originally written?",            correct: "Greek",                       opts: ["Greek",                       "Latin",                    "Hebrew",                "Aramaic"]                      },
    { q: "In Hinduism, what is the name of the supreme cosmic reality?",          correct: "Brahman",                     opts: ["Brahman",                     "Vishnu",                   "Shiva",                 "Atman"]                        },
    { q: "What is the Bhagavad Gita part of?",                                    correct: "The Mahabharata",             opts: ["The Mahabharata",             "The Ramayana",             "The Vedas",             "The Upanishads"]               },
    { q: "What is the Jewish New Year called?",                                    correct: "Rosh Hashanah",               opts: ["Rosh Hashanah",               "Yom Kippur",               "Passover",              "Sukkot"]                       },
    { q: "Who was the first prophet in Islam according to Islamic tradition?",     correct: "Adam",                        opts: ["Adam",                        "Ibrahim",                  "Musa",                  "Nuh"]                          },
    { q: "What is the term for the Islamic pilgrimage to Mecca?",                 correct: "Hajj",                        opts: ["Hajj",                        "Umrah",                    "Ziyara",                "Tawaf"]                        },
    { q: "In Buddhism, what does 'Nirvana' represent?",                           correct: "Liberation from suffering",    opts: ["Liberation from suffering",   "The highest heaven",       "Cycle of rebirth",      "A divine state"]               },
    { q: "Which city is sacred to Judaism, Christianity, and Islam?",             correct: "Jerusalem",                   opts: ["Jerusalem",                   "Mecca",                    "Vatican City",          "Varanasi"]                     },
    { q: "Which angel is said to have revealed the Quran to Muhammad?",           correct: "Jibreel (Gabriel)",           opts: ["Jibreel (Gabriel)",           "Mikael (Michael)",         "Israfil",               "Azrael"]                       },
    { q: "What are the Upanishads?",                                              correct: "Ancient Hindu philosophical texts", opts: ["Ancient Hindu philosophical texts","Hindu prayers","Vedic ritual hymns","Hindu law codes"]             },
    { q: "What is the Sikh holy book called?",                                    correct: "Guru Granth Sahib",           opts: ["Guru Granth Sahib",           "Adi Granth",               "Dasam Granth",          "Japji Sahib"]                  },
    { q: "In which city is the Golden Temple, the holiest Sikh shrine?",         correct: "Amritsar",                    opts: ["Amritsar",                    "Delhi",                    "Varanasi",              "Lahore"]                       },
  ],
  hard: [
    { q: "In which year did the Hijra (Muhammad's migration from Mecca to Medina) occur?",  correct: "622 CE",               opts: ["622 CE",               "615 CE",             "630 CE",              "610 CE"]                     },
    { q: "How many books are in the Old Testament (Protestant Bible)?",                     correct: "39",                   opts: ["39",                  "46",                 "27",                  "33"]                         },
    { q: "Which council established the biblical canon accepted by most churches?",         correct: "Council of Carthage",  opts: ["Council of Carthage", "Council of Nicaea",  "Council of Trent",    "Council of Ephesus"]         },
    { q: "What does the word 'Islam' mean in Arabic?",                                     correct: "Submission (to God)",  opts: ["Submission (to God)", "Peace",              "Faith",               "Prayer"]                     },
    { q: "Which religion follows the 'Noble Eightfold Path'?",                             correct: "Buddhism",             opts: ["Buddhism",            "Hinduism",           "Jainism",             "Taoism"]                     },
    { q: "In which year did the Great Schism divide Christianity?",                        correct: "1054 CE",              opts: ["1054 CE",             "1095 CE",            "1000 CE",             "1204 CE"]                    },
    { q: "In Judaism, what is the Talmud?",                                                correct: "Oral law commentary",  opts: ["Oral law commentary", "The Hebrew Bible",   "A prayer book",       "A collection of psalms"]     },
    { q: "How many books are in the New Testament?",                                       correct: "27",                   opts: ["27",                  "24",                 "30",                  "33"]                         },
    { q: "What is the Dalai Lama the spiritual leader of?",                                correct: "Tibetan Buddhism",     opts: ["Tibetan Buddhism",    "Theravada Buddhism", "Zen Buddhism",        "Mahayana Buddhism"]          },
    { q: "In which year was the Prophet Muhammad born according to traditional sources?",  correct: "570 CE",               opts: ["570 CE",              "555 CE",             "580 CE",              "610 CE"]                     },
    { q: "Which religion regards the Vedas as the oldest sacred texts?",                   correct: "Hinduism",             opts: ["Hinduism",            "Buddhism",           "Jainism",             "Sikhism"]                    },
    { q: "What is the significance of Laylat al-Qadr in Islam?",                          correct: "The night the Quran was first revealed", opts: ["The night the Quran was first revealed","The Prophet's birthday","The night of Isra and Mi'raj","The first night of Ramadan"] },
    { q: "How many Rakats are in the Fajr (dawn) prayer in Islam?",                       correct: "2",                    opts: ["2",                   "3",                  "4",                   "5"]                          },
    { q: "Which Jewish holy day is known as the 'Day of Atonement'?",                     correct: "Yom Kippur",           opts: ["Yom Kippur",          "Rosh Hashanah",      "Passover",            "Sukkot"]                     },
  ],
};

// Visual deception: near-identical emojis or misleading descriptions
// Uses emoji options (kind: 'emoji') for rendering
export const VISUAL_BANK: Record<'easy' | 'medium' | 'hard', TriviaQ[]> = {
  easy: [
    { q: "Which of these is the SUN — not a moon or star?",            correct: "☀️", opts: ["☀️", "🌕", "⭐", "🌟"]  },
    { q: "Which is a LION — not a tiger or fox?",                       correct: "🦁", opts: ["🦁", "🐯", "🐆", "🦊"]  },
    { q: "Which emoji is a GUITAR — not another instrument?",           correct: "🎸", opts: ["🎸", "🎺", "🎻", "🥁"]  },
    { q: "Which shows FIRE — not an explosion or lightning?",           correct: "🔥", opts: ["🔥", "💥", "⚡", "🌋"]  },
    { q: "Which is a SNOWFLAKE — not a star or sparkle?",               correct: "❄️", opts: ["❄️", "⭐", "✨", "💎"]  },
    { q: "Which emoji is a ROCKET — not a plane or UFO?",               correct: "🚀", opts: ["🚀", "✈️", "🛸", "🚁"]  },
    { q: "Which shows a TROPHY — not a medal or crown?",                correct: "🏆", opts: ["🏆", "🎖️", "🥇", "👑"]  },
    { q: "Which emoji is a CROWN — not a hat or trophy?",               correct: "👑", opts: ["👑", "🎩", "⭐", "🏆"]  },
    { q: "Which is a DRAGON — not a lizard or dinosaur?",               correct: "🐉", opts: ["🐉", "🦎", "🦕", "🐊"]  },
    { q: "Which shows a DIAMOND — not a gem or shape?",                 correct: "💎", opts: ["💎", "🔷", "🔹", "💠"]  },
  ],
  medium: [
    { q: "Which emoji is a WOLF — not a dog or fox?",                   correct: "🐺", opts: ["🐺", "🦊", "🐶", "🦮"]  },
    { q: "Which shows LIGHTNING — not an explosion or fire?",           correct: "⚡", opts: ["⚡", "💥", "🔥", "✨"]  },
    { q: "Which of these is a MOSQUE — not a church or temple?",        correct: "🕌", opts: ["🕌", "⛪", "🛕", "🕍"]  },
    { q: "Which emoji is a BRAIN — not a thought bubble or lightbulb?", correct: "🧠", opts: ["🧠", "💭", "🧬", "💡"]  },
    { q: "Which shows a MICROSCOPE — not a telescope or magnifier?",    correct: "🔬", opts: ["🔬", "🔭", "🧫", "🔍"]  },
    { q: "Which emoji represents a COMPASS — not a clock or map?",      correct: "🧭", opts: ["🧭", "⏱️", "🗺️", "📡"]  },
    { q: "Which shows a TORNADO — not a wave or wind?",                 correct: "🌪️", opts: ["🌪️", "🌊", "💨", "🌀"]  },
    { q: "Which emoji shows a STETHOSCOPE — not a syringe or bandage?", correct: "🩺", opts: ["🩺", "💉", "🩹", "🏥"]  },
    { q: "Which is a MAGNET — not a wrench or hook?",                   correct: "🧲", opts: ["🧲", "🔩", "⚙️", "🪝"]  },
    { q: "Which emoji is a SATELLITE — not a radio or antenna?",        correct: "🛰️", opts: ["🛰️", "📡", "📻", "🔭"]  },
  ],
  hard: [
    { q: "Which emoji is a MOOSE — not a deer or elk?",                 correct: "🫎", opts: ["🫎", "🦌", "🐮", "🐐"]  },
    { q: "Which shows a BEAVER — not an otter or rat?",                 correct: "🦫", opts: ["🦫", "🦦", "🐀", "🐹"]  },
    { q: "Which emoji represents CORAL — not a plant or seaweed?",     correct: "🪸", opts: ["🪸", "🌿", "🪴", "🌱"]  },
    { q: "Which is a JELLYFISH — not a squid or octopus?",             correct: "🪼", opts: ["🪼", "🦑", "🐙", "🦐"]  },
    { q: "Which emoji shows a MAMMOTH — not an elephant or rhino?",    correct: "🦣", opts: ["🦣", "🐘", "🦏", "🦛"]  },
    { q: "Which is a BISON — not a cow or bull?",                       correct: "🦬", opts: ["🦬", "🐄", "🐂", "🐃"]  },
    { q: "Which shows a COCKROACH — not a beetle or ant?",             correct: "🪳", opts: ["🪳", "🪲", "🐜", "🦗"]  },
    { q: "Which emoji is a FLY — not a bee or mosquito?",              correct: "🪰", opts: ["🪰", "🐝", "🦟", "🦗"]  },
    { q: "Which is a MAGIC WAND — not a baton or chopstick?",          correct: "🪄", opts: ["🪄", "🎺", "🥢", "✏️"]  },
    { q: "Which emoji shows a BOOMERANG — not a sword or knife?",      correct: "🪃", opts: ["🪃", "🗡️", "⚔️", "🔪"]  },
  ],
};
