import { Router, type IRouter } from "express";
import healthRouter        from "./health.js";
import authRouter          from "./auth.js";
import piAuthRouter        from "./pi-auth.js";
import playersRouter       from "./players.js";
import matchesRouter       from "./matches.js";
import communityRouter     from "./community.js";
import economyRouter       from "./economy.js";
import notificationsRouter from "./notifications.js";
import messagesRouter      from "./messages.js";
import analyticsRouter     from "./analytics.js";
import followersRouter     from "./followers.js";
import marketplaceRouter   from "./marketplace.js";
import securityRouter      from "./security.js";
import piPaymentsRouter    from "./pi-payments.js";
import betaRouter          from "./beta.js";
import monitorRouter       from "./monitor.js";
import releaseRouter       from "./release.js";
import leagueSystemRouter  from "./league-system.js";
import gameLayerRouter     from "./game-layer.js";
import arenasRouter        from "./arenas.js";
import dailyEconomyRouter  from "./daily-economy.js";
import auditRouter         from "./audit.js";
import economyBalanceRouter    from "./economy-balance.js";
import economyStabilizerRouter from "./economy-stabilizer.js";
import socialRouter            from "./social.js";
import storiesRouter           from "./stories.js";
import jobsRouter              from "./jobs.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(piAuthRouter);
router.use(arenasRouter);
router.use(playersRouter);
router.use(matchesRouter);
router.use(communityRouter);
router.use(economyRouter);
router.use(notificationsRouter);
router.use(messagesRouter);
router.use(analyticsRouter);
router.use(followersRouter);
router.use(marketplaceRouter);
router.use(securityRouter);
router.use(piPaymentsRouter);
router.use(betaRouter);
router.use(monitorRouter);
router.use(releaseRouter);
router.use(leagueSystemRouter);
router.use(gameLayerRouter);
router.use(dailyEconomyRouter);
router.use(auditRouter);
router.use(economyBalanceRouter);
router.use(economyStabilizerRouter);
router.use(socialRouter);
router.use(storiesRouter);
router.use(jobsRouter);

export default router;
